src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nomSession = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\Column]
    private ?int $nbPlaces = null;

    #[ORM\ManyToOne(inversedBy: 'Sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formation $Formation = null;

    #[ORM\ManyToOne(inversedBy: 'Sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formateur $Formateur = null;

    /**
     * @var Collection<int, Stagiaire>
     */
    #[ORM\ManyToMany(targetEntity: Stagiaire::class, mappedBy: 'Sessions')]
    private Collection $Stagiaires;

    /**
     * @var Collection<int, Programme>
     */
    #[ORM\OneToMany(targetEntity: Programme::class, mappedBy: 'Session')]
    private Collection $Programmes;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    public function __construct()
    {
        $this->Stagiaires = new ArrayCollection();
        $this->Programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSession(): ?string
    {
        return $this->nomSession;
    }

    public function setNomSession(string $nomSession): static
    {
        $this->nomSession = $nomSession;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateDebutFr(): ?string
    {
        return $this->dateDebut->format("d/m/Y");
    }

    public function getHeureDebutFr(): ?string
    {
        return $this->dateDebut->format("H:i");
    }


    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getDateFinFr(): ?string
    {
        return $this->dateFin->format("d/m/Y");
    }

    public function getHeureFinFr(): ?string
    {
        return $this->dateFin->format("H:i");
    }


    public function getNbPlaces(): ?int
    {
        return $this->nbPlaces;
    }

    public function setNbPlaces(int $nbPlaces): static
    {
        $this->nbPlaces = $nbPlaces;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->Formation;
    }

    public function setFormation(?Formation $Formation): static
    {
        $this->Formation = $Formation;

        return $this;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->Formateur;
    }

    public function setFormateur(?Formateur $Formateur): static
    {
        $this->Formateur = $Formateur;

        return $this;
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getStagiaires(): Collection
    {
        return $this->Stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): static
    {
        if (!$this->Stagiaires->contains($stagiaire)) {
            $this->Stagiaires->add($stagiaire);
            $stagiaire->addSession($this);
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): static
    {
        if ($this->Stagiaires->removeElement($stagiaire)) {
            $stagiaire->removeSession($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->Programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->Programmes->contains($programme)) {
            $this->Programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->Programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNomSession();
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Repository\SessionRepository;
use App\Repository\FormationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    #[Route('/dashboard', name: 'app_dashboard')]
    public function index(FormationRepository $formationRepository, SessionRepository $sessionRepository, EntityManagerInterface $entityManager): Response
    {
        $formations = $formationRepository->findAll();

        $query = $sessionRepository->createQueryBuilder('s')
            ->select('s')
            ->where('s.dateFin > :now')
            ->andWhere('s.dateDebut < :now')
            ->setParameter('now', new \DateTime())
            ->orderBy('s.dateFin', 'ASC')
            ->getQuery();
        $sessionsEnCours = $query->setMaxResults(4)->getResult();


        $query = $sessionRepository->createQueryBuilder('s')
            ->select('s')
            ->where('s.dateDebut > :now')
            ->setParameter('now', new \DateTime())
            ->orderBy('s.dateDebut', 'ASC')
            ->getQuery();
        $sessionsProchaines = $query->setMaxResults(2)->getResult();

        return $this->render('home/index.html.twig', [
            'sessionsEnCours' => $sessionsEnCours,
            'sessionsProchaines' => $sessionsProchaines,
            'formations' => $formations
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard{% endblock %}

{% block body %}


<section id="en-cours">
    <h2>En Cours</h2>
    <div class="line"></div>

    {% if sessionsEnCours | length > 0 %}
        <div class="dashboard-sessions">
            <div class="line-2"></div>
            {% for session in sessionsEnCours %}
                <div class="dashboard-session">
                    <h4>{{ session.formation }}</h3>
                    <h3>{{ session }}</h2>
                    <p>{{ session.description }}</p>
                    <p>{{ session.nbPlaces }} places restantes</p>
                    <p>Du {{ session.dateDebutFr }}</p>
                    <p>Au {{ session.dateFinFr }}</p>
                    <a class="primary" href="{{ path('show_session', {'id': session.id}) }}">En savoir plus</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Aucune session en cours</p>
    {% endif %}

</section>


<section id="prochainement">
    <h2>Prochainement</h2>
    <div class="line"></div>

    <div class="dashboard-sessions">
        <div class="line-2"></div>
        {% for session in sessionsProchaines %}
            <div class="dashboard-session">
                {% if session.nbPlaces == 0 %}
                    <div class="complet">Complet</div> 
                {% endif %}
                <h4>{{ session.formation }}</h3>
                <h3>{{ session }}</h2>
                <p>{{ session.description }}</p>
                <p>{{ session.nbPlaces }} places restantes</p>
                <p>Du {{ session.dateDebutFr }}</p>
                <p>Au {{ session.dateFinFr }}</p>
                <a class="primary" href="{{ path('show_session', {'id': session.id}) }}">En savoir plus</a>
            </div>
        {% endfor %}
    </div>

</section>

<section id="dashboard-formations">
    <h2>Formations</h2>
    <div class="line"></div>

    <div class="wrapper-formations">
        {% for formation in formations %}
            <div class="list dashboard-formation">
                <a href="{{ path('show_formation', {'id': formation.id}) }}">
                    <h3>{{ formation }}</h3>
                    {% for session in formation.sessions %}
                        {{ session }}
                        {% if not loop.last %} - {% endif %}
                    {% endfor %}
                </a>
            </div>
        {% endfor %}
    </div>
</section>

{% endblock %}