src/Entity/Programme.php
<?php

namespace App\Entity;

use App\Repository\ProgrammeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProgrammeRepository::class)]
class Programme
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $nbJours = null;

    #[ORM\ManyToOne(inversedBy: 'Programmes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Session $Session = null;

    #[ORM\ManyToOne(inversedBy: 'Programmes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Unite $Unite = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbJours(): ?int
    {
        return $this->nbJours;
    }

    public function setNbJours(int $nbJours): static
    {
        $this->nbJours = $nbJours;

        return $this;
    }

    public function getSession(): ?Session
    {
        return $this->Session;
    }

    public function setSession(?Session $Session): static
    {
        $this->Session = $Session;

        return $this;
    }

    public function getUnite(): ?Unite
    {
        return $this->Unite;
    }

    public function setUnite(?Unite $Unite): static
    {
        $this->Unite = $Unite;

        return $this;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nomSession = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\Column]
    private ?int $nbPlaces = null;

    #[ORM\ManyToOne(inversedBy: 'Sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formation $Formation = null;

    #[ORM\ManyToOne(inversedBy: 'Sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formateur $Formateur = null;

    /**
     * @var Collection<int, Stagiaire>
     */
    #[ORM\ManyToMany(targetEntity: Stagiaire::class, mappedBy: 'Sessions')]
    private Collection $Stagiaires;

    /**
     * @var Collection<int, Programme>
     */
    #[ORM\OneToMany(targetEntity: Programme::class, mappedBy: 'Session')]
    private Collection $Programmes;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    public function __construct()
    {
        $this->Stagiaires = new ArrayCollection();
        $this->Programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSession(): ?string
    {
        return $this->nomSession;
    }

    public function setNomSession(string $nomSession): static
    {
        $this->nomSession = $nomSession;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->dateDebut;
    }

    public function setDateDebut(\DateTimeInterface $dateDebut): static
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    public function getDateDebutFr(): ?string
    {
        return $this->dateDebut->format("d/m/Y");
    }

    public function getHeureDebutFr(): ?string
    {
        return $this->dateDebut->format("H:i");
    }


    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getDateFinFr(): ?string
    {
        return $this->dateFin->format("d/m/Y");
    }

    public function getHeureFinFr(): ?string
    {
        return $this->dateFin->format("H:i");
    }


    public function getNbPlaces(): ?int
    {
        return $this->nbPlaces;
    }

    public function setNbPlaces(int $nbPlaces): static
    {
        $this->nbPlaces = $nbPlaces;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->Formation;
    }

    public function setFormation(?Formation $Formation): static
    {
        $this->Formation = $Formation;

        return $this;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->Formateur;
    }

    public function setFormateur(?Formateur $Formateur): static
    {
        $this->Formateur = $Formateur;

        return $this;
    }

    /**
     * @return Collection<int, Stagiaire>
     */
    public function getStagiaires(): Collection
    {
        return $this->Stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): static
    {
        if (!$this->Stagiaires->contains($stagiaire)) {
            $this->Stagiaires->add($stagiaire);
            $stagiaire->addSession($this);
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): static
    {
        if ($this->Stagiaires->removeElement($stagiaire)) {
            $stagiaire->removeSession($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->Programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->Programmes->contains($programme)) {
            $this->Programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->Programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNomSession();
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Formateur;
use App\Entity\Formation;
use App\Entity\Stagiaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nomSession', TextType::class, [
                'label' => 'Nom de la session : ',
                'attr' => [
                    'class' => 'form'
                ]
            ])
            ->add('dateDebut', DateTimeType::class, [
                'html5' => false,
                'label' => 'Date de début :',
                'label_attr' => ['class' => 'label'],
                'years' => range(date("Y"), date("Y") + 5),
                'format' => 'dd MM yyyy | H:i',
                'attr' => [
                    'class' => 'form date'
                ]
            ])
            ->add('dateFin', DateTimeType::class, [
                'html5' => false,
                'label' => 'Date de fin :',
                'label_attr' => ['class' => 'label'],
                'years' => range(date("Y"), date("Y") + 5),
                'format' => 'dd MM yyyy | H:i',
                'attr' => [
                    'class' => 'form date'
                ]
            ])
            ->add('nbPlaces', NumberType::class, [
                'label' => 'Nombre de places : ',
                'attr' => [
                    'class' => 'form'
                ]
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description : ',
                'attr' => [
                    'class' => 'form'
                ]
            ])
            ->add('Formation', EntityType::class, [
                'class' => Formation::class,
                'choice_label' => 'titreFormation',
                'attr' => [
                    'class' => 'form'
                ]

            ])
            ->add('Formateur', EntityType::class, [
                'class' => Formateur::class,
                'choice_label' => 'fullnameFormateur',
                'attr' => [
                    'class' => 'form'
                ]

            ])
            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'submit btn'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use Doctrine\ORM\Mapping\Entity;
use Exception;
use App\Entity\Session;
use App\Entity\Programme;
use App\Entity\Stagiaire;
use App\Form\SessionType;
use App\Form\ProgrammeType;
use App\Repository\SessionRepository;
use App\Repository\FormationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SessionController extends AbstractController
{
    #[Route('/session', name: 'app_session')]
    public function index(SessionRepository $sessionRepository, FormationRepository $formationRepository): Response
    {
        $formations = $formationRepository->findAll();
        return $this->render('session/index.html.twig', [
            'formations' => $formations
        ]);
    }

    #[Route('/session/new', name: 'new_session')]
    #[Route('/session/{id}/edit', name: 'edit_session')]
    public function new_edit(Session $session = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        $isNewSession = !$session;
        $message = $isNewSession ? 'Session créée' : 'Session modifiée';

        if (!$session) {
            $session = new Session();
        }

        $form = $this->createForm(SessionType::class, $session);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $session = $form->getData();
            $entityManager->persist($session);
            $entityManager->flush();
            $this->addFlash('success', $message);
            return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
        }

        return $this->render("session/new.html.twig", [
            'formAddSession' => $form,
            'edit' => $session->getId()
        ]);
    }

    #[Route('/session/{id}/delete', name: 'delete_session')]
    public function delete(Session $session, EntityManagerInterface $entityManager): Response
    {
        $entityManager->remove($session);
        $entityManager->flush();
        $this->addFlash('success', 'Session supprimée');
        return $this->redirectToRoute('app_session');
    }

    #[Route('/session/{id}/{id_stagiaire}/registerStagiaire', name: 'registerStagiaire')]
    public function registerStagiaire(Session $session, int $id_stagiaire, EntityManagerInterface $entityManager): Response
    {
        $stagiaire = $entityManager->getRepository(Stagiaire::class)->find($id_stagiaire);

        if ($session->getNbPlaces() > 0) {
            $session->addStagiaire($stagiaire);
            $session->setNbPlaces($session->getNbPlaces() - 1);
            $entityManager->flush();
            flash()->addSuccess('Stagiaire incrit');
        } else {
            flash()->addError('Aucune place disponible');
        }
        return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
    }


    #[Route('/session/{id}/{id_stagiaire}/unregisterStagiaire', name: 'unregisterStagiaire')]
    public function unregisterStagiaire(Session $session, int $id_stagiaire, EntityManagerInterface $entityManager): Response
    {
        $stagiaire = $entityManager->getRepository(Stagiaire::class)->find($id_stagiaire);

        $session->removeStagiaire($stagiaire);
        $session->setNbPlaces($session->getNbPlaces() + 1);
        $entityManager->flush();
        $this->addFlash('success', 'Stagiaire désinscrit');
        return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
    }


    #[Route('/session/{id}', name: 'show_session')]
    public function show(Session $session, Request $request, EntityManagerInterface $entityManager): Response
    {
        $programme = new Programme();
        $programme->setSession($session);

        $moduleForm = $this->createForm(ProgrammeType::class, $programme);

        $moduleForm->handleRequest($request);
        if ($moduleForm->isSubmitted() && $moduleForm->isValid()) {
            $programme = $moduleForm->getData();
            $entityManager->persist($programme);
            $entityManager->flush();
            $this->addFlash('success', 'Programme ajouté');

            return $this->redirectToRoute('show_session', ['id' => $session->getId()]);
        }

        $query = $entityManager->getRepository(Stagiaire::class)->createQueryBuilder('s')
            ->select('s')
            ->where(':session NOT MEMBER OF s.Sessions')
            ->setParameter('session', $session)
            ->orderBy('s.nomStagiaire', 'ASC')
            ->getQuery();
        $stagiaires = $query->getResult();

        return $this->render("session/show.html.twig", [
            'moduleForm' => $moduleForm,
            'stagiaires' => $stagiaires,
            'session' => $session,
        ]);
    }

}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste de sessions{% endblock %}

{% block body %}

<div class="titre">
    <h1>Sessions</h1>
    {% if is_granted('ROLE_ADMIN') %}
        <a class="btn" href="{{ path('new_session')}}">Ajouter une session</a>
    {% endif %}
</div>
<div class="line"></div>

{% for formation in formations %}
        
    <div class="sous-titre">
        <h2>{{ formation }}</h2>
    </div>

    {% if formation.sessions | length > 0 %}
        {% for session in formation.sessions %}
            <div class="list session">
                <div class="text">
                    <a href="{{ path('show_session', {'id': session.id}) }}">
                        <h3>{{ session.nomSession }}</h3>
                        {{ session.nbPlaces }} {% if session.nbPlaces == 1 %} place {% else %} places {% endif %}restantes
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        Aucune sessions
    {% endif %}
{% endfor %}




{% endblock %}

templates/session/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{% if edit %}
Editer une session
{% else %}
Ajouter une session
{% endif %}
{% endblock %}

{% block body %}
    {% if edit %}
    <h1>Editer une session</h1>
    <div class="line"></div>
          
    {% else %}
    <h1>Ajouter une session</h1>
    <div class="line"></div>
    {% endif %}

    {{ form(formAddSession) }}

{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ session }}{% endblock %}

{% block body %}
<div class="titre">
<h1>{{ session }}</h1>
{% if is_granted('ROLE_ADMIN') %}
    <div class="btns">
        <a class="btn" href="{{ path('edit_session', {'id': session.id}) }}">Modifier</a>
        <a class="btn delete" href="{{ path('delete_session', {'id': session.id}) }}">Supprimer</a>
    </div>
{% endif %}
</div>
<div class="line"></div>

<section id="session-info">
    <div class="fiche">
        <h3>Informations :</h3>
        <p>Encadré par {{ session.formateur }}</p>
        {% if session.description | length > 0 %}
            <p>{{ session.description }}</p>
        {% endif %}
        <p>Du {{ session.dateDebutFr }} à {{ session.heureDebutFr }} </p><p> Au {{ session.dateFinFr }} à {{ session.heureFinFr }}</p>
        <p>Nombre de places : {{ session.nbPlaces }}</p>
    </div>
</section>

<section id="modules">
    <div class="sous-titre">
        <h2>Modules :</h2>
        {% if is_granted('ROLE_ADMIN') %}
            <button id="toggle-module" class="btn">Ajouter un module</button>
        {% endif %}
    </div>
    <div id="module-form" class="form-toggle">
        {{ form(moduleForm) }}
    </div>


    {% if session.programmes | length > 0 %}

        <table>
            <thead>
                <tr>
                    <th>Module</th>
                    <th>Jours</th>
                    {% if is_granted('ROLE_ADMIN') %}
                    <th>Supprimer</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>

            {% for programme in session.programmes %}
                <tr>
                    <td><strong>{{ programme.unite }}</strong></td>
                    <td>{{ programme.nbJours }}</td>
                    {% if is_granted('ROLE_ADMIN') %}
                    <td><a class="btn delete" href="{{ path('delete_programme', {'id': programme.id}) }}">Supprimer</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
                        
            </tbody>
        </table>

    {% else %}
        <p>Aucun module disponible</p>
    {% endif %}

</section>

<section id="session-stagiaires">
    <div class="sous-titre">
        <h2>Stagiaires inscrits :</h2>
        {% if is_granted('ROLE_ADMIN') %}
            <button id="toggle-stagiaire" class="btn">Ajouter un stagiaire</button>
        {% endif %}
    </div>
    <div id="stagiaire-form" class="form-toggle">
        {% for stagiaire in stagiaires %}
            <div class="list session">
                <div class="text">
                    <a href="{{ path('show_stagiaire', {'id': stagiaire.id }) }}"><h3>{{ stagiaire }}</h3></a>
                    <p>{{ stagiaire.emailStagiaire }}</p> 
                </div>
                    <a class="btn" href="{{ path('registerStagiaire', {'id': session.id, 'id_stagiaire': stagiaire.id | number_format }) }}">Inscrire</a>
            </div>
        {% endfor %}
    </div>

    {% if session.stagiaires | length > 0 %}

    <table>
        <thead>
            <tr>
                <th>Stagiaire</th>
                <th>Email</th>
                {% if is_granted('ROLE_ADMIN') %}
                    <th>Désinscrire</th>
                {% endif %}
            </tr>
        </thead>

        <tbody>
        {% for stagiaire in session.stagiaires %}
            <tr>
                <td><a href="{{ path('show_stagiaire', {'id': stagiaire.id }) }}"><strong>{{ stagiaire }}</strong></a></td>
                <td>{{ stagiaire.emailStagiaire }}</td>
                {% if is_granted('ROLE_ADMIN') %}
                    <td><a class="btn delete" href="{{ path('unregisterStagiaire', {'id': session.id, 'id_stagiaire': stagiaire.id | number_format }) }}">Désinscrire</a></td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% else %}
    <p>Aucun stagiaires inscrits</p>
{% endif %}

</section>

{% endblock %}