src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nomCategorie = null;

    /**
     * @var Collection<int, Unite>
     */
    #[ORM\OneToMany(targetEntity: Unite::class, mappedBy: 'Categorie')]
    private Collection $Unites;

    public function __construct()
    {
        $this->Unites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nomCategorie;
    }

    public function setNomCategorie(string $nomCategorie): static
    {
        $this->nomCategorie = $nomCategorie;

        return $this;
    }

    /**
     * @return Collection<int, Unite>
     */
    public function getUnites(): Collection
    {
        return $this->Unites;
    }

    public function addUnite(Unite $unite): static
    {
        if (!$this->Unites->contains($unite)) {
            $this->Unites->add($unite);
            $unite->setCategorie($this);
        }

        return $this;
    }

    public function removeUnite(Unite $unite): static
    {
        if ($this->Unites->removeElement($unite)) {
            // set the owning side to null (unless already changed)
            if ($unite->getCategorie() === $this) {
                $unite->setCategorie(null);
            }
        }

        return $this;
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Repository\CategorieRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CategorieController extends AbstractController
{
    #[Route('/categorie', name: 'app_categorie')]
    public function index(CategorieRepository $categorieRepository): Response
    {
        $categories = $categorieRepository->findBy([], ["nomCategorie" => "ASC"]);
        return $this->render('categorie/index.html.twig', [
            'categories' => $categories,
        ]);
    }

    #[Route('/categorie/{id}', name: 'show_categorie')]
    public function show(Categorie $categorie): Response
    {
        return $this->render("categorie/show.html.twig", [
            'categorie' => $categorie,
        ]);
    }

}

templates/categorie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des categories{% endblock %}

{% block body %}
<div class="titre">
    <h1>Liste des categories</h1>
</div>
<div class="line"></div>


    {% for categorie in categories %}
    <div class="list categorie">
        <a href="{{ path('show_categorie', {'id': categorie.id}) }}">
            <h3>{{ categorie.nomCategorie }}</h3>
        </a>
    </div class="list categorie"> 
    {% endfor %}


{% endblock %}

templates/categorie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ categorie.nomCategorie }}{% endblock %}

{% block body %}
<div class="titre">
<h1>{{ categorie.nomCategorie }}</h1>
</div>
<div class="line"></div>

<h2>Modules</h2>

{% if categorie.unites | length > 0 %}

{% for unite in categorie.unites %}
    <div class="list unite">
        <h3>{{ unite }}</h3>
    </div>
{% endfor %}

{% else %}
    <p>Aucun module</p>
{% endif %}

{% endblock %}